### ISSUE TITLE
add workshop host names to /etc/hosts and to system running vagrant

### ISSUE THREAD

**Issue by dbu** [netgen/summercamp-2015#14]
we should have all the hosts defined. inside the box this is simply having a file that adds to `/etc/hosts` when creating the box and pointing them all to 127.0.0.1

for the main system, there are hostname plugins for vagrant. not sure if those can be used to provide more than one name for the machine, as you need to make the apache vhosts work.

**Comment by vranac** [comment]
OK, lets sort this out, which need to point to 127.0.0.1 for your workshop? 
I'll add them during the day

**Comment by emodric** [comment]
@vranac You should add ALL workshop domains to `/etc/hosts`, not just the ones specific to @dbu 's workshop.

**Comment by vranac** [comment]
Sure, will be sorted

**Comment by dbu** [comment]
inside the box, every hostname you have in the google spreadsheet should
be pointing to 127.0.0.1

if you also manage to add the names to the hosts file of the host
machine, that would be cool but not sure if its easy.

**Comment by vranac** [comment]
All hostnames added in #23
