### ISSUE TITLE
Submodules as HTTPS instead of SSH Links

### ISSUE THREAD

**Issue by kuborgh-mspindelhirn** [netgen/summercamp-2015#22]
When using git or ssh urls for submodules and you want to run the run.sh from within you box you will need to configure git with a public key. 
If you only use HTTPS references and the repositories are all public this is no longer needed, is it?

**Comment by vranac** [comment]
Your host machine keys will be used with vagrant, as it uses agent forwarding, so ti makes no difference.

**Comment by kuborgh-mspindelhirn** [comment]
Right. Did not work for me but that should be a problem on my side. Thanks for clarification ;)
