### ISSUE TITLE
VM provisioning fails with VirtualBox 5

### ISSUE THREAD

**Issue by gggeek** [netgen/summercamp-2015#40]
It seems that the bundled VirtualBox tools fail to do the mounting of the shared folders.

Here is the end of cli output of vagrant up:

==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 4.3.10
    default: VirtualBox Version: 5.0
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => D:/htdocs/summercamp2015
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

chown `id -u vagrant`:`id -g vagrant` /vagrant

Stdout from the command:

Stderr from the command:

chown: changing ownership of ���/vagrant���: Not a directory

**Comment by vranac** [comment]
Please go to the helpdesk, in the elephant room, on the left hand side, when you enter it

**Comment by gggeek** [comment]
Thx - trying to fix it by myself first

**Comment by gggeek** [comment]
VBox Additions updated, still the shared folders are not mounting :-(

d:\htdocs\summercamp2015>vagrant up --no-provision
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: password
    default: Warning: Connection timeout. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => D:/htdocs/summercamp2015
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

chown `id -u vagrant`:`id -g vagrant` /vagrant

Stdout from the command:

Stderr from the command:

chown: changing ownership of ���/vagrant���: Not a directory

**Comment by gggeek** [comment]
Grr, seems like a bug with Vagrant 1.7.3...

https://github.com/mitchellh/vagrant/issues/5933

**Comment by vranac** [comment]
You should use 1.7.4 as noted in the readme.md

—

**Comment by gggeek** [comment]
My bad, did not see it... (nitpick: 'recommended' => 'required', at least on windows)
